blank_issues_enabled: false
contact_links:
  - name: Discuss libcheloniajs
    url: https://github.com/okTurtles/libcheloniajs/discussions
    about: Use issues to report bugs or request features. Everything else goes here.
    